/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_hayukleung_jni_fibonacci_IFibonacci.h"
#include "fibonacci/Fibonacci.h"
/* Header for class com_hayukleung_jni_fibonacci_IFibonacci */

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hayukleung_jni_fibonacci_IFibonacci
 * Method:    getFibonacci
 * Signature: (J)J
 */
JNIEXPORT uint64_t JNICALL Java_com_hayukleung_jni_fibonacci_IFibonacci_getFibonacci
        (JNIEnv *env, jobject object, uint64_t index, jint type) {
    switch (type) {
        case 1:
            return recursive_1(index);
        case 2:
            return recursive_2(index);
        case 3:
            return iterative_1(index);
        case 4:
            return iterative_2(index);
    }
    return -1;
}

#ifdef __cplusplus
}
#endif
