/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_hayukleung_jni_callback_ICallback */

#ifndef _Included_com_hayukleung_jni_callback_ICallback
#define _Included_com_hayukleung_jni_callback_ICallback
#ifdef __cplusplus
extern "C" {
#endif

#define LOG(...) __android_log_print(ANDROID_LOG_DEBUG, "native", __VA_ARGS__)

/*
 * Class:     com_hayukleung_jni_callback_ICallback
 * Method:    callback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hayukleung_jni_callback_ICallback_callback
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
