/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hayukleung_jni_callback_ICallback */

#ifndef _Included_com_hayukleung_jni_callback_ICallback
#define _Included_com_hayukleung_jni_callback_ICallback
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hayukleung_jni_callback_ICallback
 * Method:    callback
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_hayukleung_jni_callback_ICallback_callback
        (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
