/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdint.h>
/* Header for class com_hayukleung_jni_fibonacci_IFibonacci */

#ifndef _Included_com_hayukleung_jni_fibonacci_IFibonacci
#define _Included_com_hayukleung_jni_fibonacci_IFibonacci
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hayukleung_jni_fibonacci_IFibonacci
 * Method:    getFibonacci
 * Signature: (JI)J
 */
JNIEXPORT uint64_t JNICALL Java_com_hayukleung_jni_fibonacci_IFibonacci_getFibonacci
        (JNIEnv *, jobject, uint64_t, jint);

#ifdef __cplusplus
}
#endif
#endif
